name: Continious deployment on master

on:
  push:
    branches: [master]
  
jobs:
  deploy:
    uses: macdrien/macdrien-cv@master
    with:
      server: ${{ secrets.FTP_SERVER }}
      user: ${{ secrets.FTP_USERNAME }}
      password: ${{ secrets.FTP_PASSWORD }}
